plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "com.modrinth.minotaur"
    id "com.matthewprenger.cursegradle"
}
def modrinthToken = System.getenv("MODRINTH_TOKEN")
def secretPropsFile = rootProject.file('publishing.properties')
def secretProps = new Properties()

if (secretPropsFile.exists()) {
    secretPropsFile.withInputStream { stream ->
        secretProps.load(stream)
    }
} else {
    logger.warn("publishing.properties file not found!")
}

def cfToken = secretProps.getProperty('curseforge_token') ?: ""

modrinth {
    token = modrinthToken
    projectId = property("modrinth_project_id").toString()
    versionNumber = version.toString()
    versionType = property("versionType").toString()
    uploadFile = tasks.findByName("remapJar") ?: tasks.named("jar")
    gameVersions = [property("minecraft_version").toString()]
    loaders = ["fabric", "quilt"]
    changelog = rootProject.file("CHANGELOG.md").text
}
curseforge {
    apiKey = cfToken

    project {
        id = property("curseforge_project_id").toString()

        mainArtifact(tasks.findByName("remapJar") ?: tasks.named("jar")) {
            displayName = "Redden's Stone Lanterns Reconstructed v${version}"
        }

        releaseType = property("versionType").toString()

        addGameVersion property("minecraft_version").toString()

        addGameVersion "Fabric"
        addGameVersion "Quilt"

        changelogType = "markdown"
        changelog = rootProject.file("CHANGELOG.md").text
    }
}
tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
    dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}
sourceSets {
    main {
        resources {
            srcDirs += project(':common').file('src/main/resources')
        }
    }
}
loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}