plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "com.modrinth.minotaur"
    id "net.darkhax.curseforgegradle"
}
tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
def modrinthToken = System.getenv("MODRINTH_TOKEN")
def secretPropsFile = rootProject.file('publishing.properties')
def secretProps = new Properties()

if (secretPropsFile.exists()) {
    secretPropsFile.withInputStream { stream ->
        secretProps.load(stream)
    }
} else {
    logger.warn("publishing.properties file not found!")
}

def cfToken = secretProps.getProperty('curseforge_token') ?: ""

modrinth {
    token = modrinthToken
    projectId = property("modrinth_project_id").toString()
    versionNumber = version.toString()
    versionType = property("versionType").toString()
    uploadFile = tasks.findByName("remapJar") ?: tasks.named("jar")
    gameVersions = [property("minecraft_version").toString()]
    loaders = ["fabric", "quilt"]
    changelog = rootProject.file("CHANGELOG.md").text

}

tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = cfToken
    def projectId = ("${curseforge_project_id}").toLong()
    def mainFile = upload(projectId, tasks.findByName("remapJar") ?: tasks.named("jar"))
    mainFile.displayName = "Redden's Stone Lanterns Reconstructed v${version}"
    mainFile.releaseType = "${versionType}"
    mainFile.changelogType = "markdown"
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addModLoader("Fabric")
    mainFile.addModLoader("Quilt")
}

tasks.named('publishCurseForge').configure {
    dependsOn tasks.findByName("remapJar") ?: tasks.named("jar")
}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}
sourceSets {
    main {
        resources {
            srcDirs += project(':common').file('src/main/resources')
        }
    }
}
loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
            vmArg "-Dfabric.remapClasspathFile=${project.buildDir}/loom-cache/remapped-classpath.txt"
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
            vmArg "-Dfabric.remapClasspathFile=${project.buildDir}/loom-cache/remapped-classpath.txt"
        }
    }
}