
version=1.0
versionType=release

# Minecraft
minecraft_version=1.21.3
minecraft_version_range=[1.21.3, 1.22)

# Fabric
fabric_version=0.116.12+1.21.3
fabric_loader_version=0.18.0
yarn_mappings=1.21.1+build.3

# Forge
forge_version=52.1.0
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.233
neoforge_loader_version_range=[21.1,)


group=dev.thenu.ReddensStoneLanternReconstructed
java_version=21

modrinth_project_id=tQG2KWRe
curseforge_project_id=1562898

mod_name=ReddensStoneLanternsReconstructed
mod_author=King_Thenuja
mod_id=reddensstonelantern
license=All-Rights-Reserved
credits=ReddenWang
description=Latest versions for Reddens Stone Lanterns

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true