
version=1.0
versionType=release

# Minecraft
minecraft_version=26.2
minecraft_version_range=[26.1, 26.2)

# Fabric
fabric_version=0.154.2+26.1.2
fabric_loader_version=0.19.0
fabric.remapClasspathFile=true

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[26.1, 26.2)

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

group=dev.thenu.ReddensStoneLanternReconstructed
java_version=25

modrinth_project_id=tQG2KWRe
curseforge_project_id=1562898

mod_name=ReddensStoneLanternsReconstructed
mod_author=King_Thenuja
mod_id=reddensstonelantern
license=All-Rights-Reserved
credits=ReddenWang
description=Latest versions for Reddens Stone Lanterns

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot