
version=1.0
versionType=release

# Minecraft
minecraft_version=1.21.8
minecraft_version_range=[1.21.8, 1.22)

# Fabric
fabric_version=0.136.1+1.21.8
fabric_loader_version=0.18.0
yarn_mappings=1.21.8+build.1

# NeoForge
neoforge_version=21.8.53
neoforge_loader_version_range=[4,)


group=dev.thenu.ReddensStoneLanternReconstructed
java_version=21

modrinth_project_id=tQG2KWRe
curseforge_project_id=1562898

mod_name=ReddensStoneLanternsReconstructed
mod_author=King_Thenuja
mod_id=reddensstonelantern
license=All-Rights-Reserved
credits=ReddenWang
description=Latest versions for Reddens Stone Lanterns

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.6.7-hotspot