modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/KingThenuja/ReddensStoneLanternsReconstructed/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://modrinth.com/mod/reddens-stone-lantern-reconstructed/versions"
logoFile="reddensstonelantern.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange="[26.1, 26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
