plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "com.modrinth.minotaur"
    id "net.darkhax.curseforgegradle"
}
def modrinthToken = System.getenv("MODRINTH_TOKEN")
def secretPropsFile = rootProject.file('publishing.properties')
def secretProps = new Properties()

if (secretPropsFile.exists()) {
    secretPropsFile.withInputStream { stream ->
        secretProps.load(stream)
    }
} else {
    logger.warn("publishing.properties file not found!")
}

def cfToken = secretProps.getProperty('curseforge_token') ?: ""

modrinth {
    token = modrinthToken
    projectId = property("modrinth_project_id").toString()
    versionNumber = version.toString()
    versionType = property("versionType").toString()
    uploadFile = tasks.findByName("remapJar") ?: tasks.named("jar")
    gameVersions = ["1.21", property("minecraft_version").toString()]
    loaders = ["neoforge"]
    changelog = rootProject.file("CHANGELOG.md").text
}
tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = cfToken
    def projectId = property("curseforge_project_id").toString()
    def mainFile = upload(projectId, tasks.findByName("remapJar") ?: tasks.named("jar"))
    mainFile.displayName = "Redden's Stone Lanterns Reconstructed v${version}"
    mainFile.releaseType = property("versionType").toString()
    mainFile.changelogType = "markdown"
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.addGameVersion("1.21")
    mainFile.addGameVersion(property("minecraft_version").toString())
    mainFile.addModLoader("NeoForge")
}

tasks.named('publishCurseForge').configure {
    dependsOn tasks.findByName("remapJar") ?: tasks.named("jar")
}

sourceSets {
    main {
        resources {
            srcDirs += project(':common').file('src/main/generated')
        }
    }
}
neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
sourceSets.main.resources { srcDir 'src/generated/resources' }
