plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "com.modrinth.minotaur"
    id "net.darkhax.curseforgegradle"
}
def modrinthToken = System.getenv("MODRINTH_TOKEN")
def secretPropsFile = rootProject.file('publishing.properties')
def secretProps = new Properties()

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
if (secretPropsFile.exists()) {
    secretPropsFile.withInputStream { stream ->
        secretProps.load(stream)
    }
} else {
    logger.warn("publishing.properties file not found!")
}

def cfToken = secretProps.getProperty('curseforge_token') ?: ""

modrinth {
    token = modrinthToken
    projectId = property("modrinth_project_id").toString()
    versionNumber = version.toString()
    versionType = property("versionType").toString()
    uploadFile = tasks.findByName("remapJar") ?: tasks.named("jar")
    gameVersions = [property("minecraft_version").toString()]
    loaders = ["neoforge"]
    changelog = rootProject.file("CHANGELOG.md").text

}
tasks.named('sourcesJar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = cfToken
    def projectId = ("${curseforge_project_id}").toLong()
    def mainFile = upload(projectId, tasks.findByName("remapJar") ?: tasks.named("jar"))
    mainFile.displayName = "Redden's Stone Lanterns Reconstructed v${version}"
    mainFile.releaseType = "${versionType}"
    mainFile.changelogType = "markdown"
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addModLoader("NeoForge")
    mainFile.addEnvironment("Client")
    mainFile.addEnvironment("Server")
}

tasks.named('publishCurseForge').configure {
    dependsOn tasks.findByName("remapJar") ?: tasks.named("jar")
}

sourceSets {
    main {
        resources {
            srcDirs += project(':common').file('src/main/generated')
        }
    }
}
neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
